# -*- coding: utf-8 -*-
"""Matplotlib1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RnGo76MOnhJXdxzvZY1lAjfvgvkrwlrR
"""

import sys
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
# load the dataset
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/s30/Telco-Customer-Churn (3).csv').drop(columns = ['customerID'])

"""# Problem 1"""

#went through this link: https://www.geeksforgeeks.org/python-introduction-matplotlib/
# Figure: Top level container

"""# Problem 2"""

import matplotlib.pyplot as plt

years = [1970, 1980, 1990, 2000, 2010, 2020]
Ind = [40, 60, 80, 120, 180, 300]
bang = [5, 10, 20, 40, 50, 70]

plt.plot(years, Ind, label = 'India', color = 'blue', marker = 'o', markersize = 6)
# plt.axis([1960, 2030, 0, 350])
plt.plot(years, bang, label = 'Bangladesh', color = 'green', linestyle = '--', linewidth = 2, marker = '^', markersize = 6)
# plt.legend(['India', 'Bangladesh'])
# plt.legend()
plt.xlabel('Years')
plt.ylabel('Electricy Consumption')
plt.title("India vs Bangladesh Electricity Consumption")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Generate random data
np.random.seed(42)
x = np.random.rand(50)
y = np.random.rand(50)
colors = np.random.rand(50)

# Create a scatter plot with color mapping
# plt.scatter(x, y, c=colors, cmap='viridis', s=100, alpha=0.8)
plt.scatter(x, y, c=colors, s=100, alpha=0.8)

# Set plot title and labels
plt.title('Scatter Plot with Color Mapping')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Display the plot
plt.show()

""" # Problem 3"""

X = np.linspace(-np.pi, np.pi, 15)
C = np.cos(X)
S = np.sin(X)

fig = plt.figure()
ax = plt.axes([0.1, 0.1, 0.8, 0.8])
# ax1 = ax.plot(X, S, 'bs:')
ax1 = ax.plot(X, S, marker = 's', color = 'blue', linestyle = ':')
ax2 = ax.plot(X,C, 'ro-')
ax.legend(labels = ('sin', 'cos'), loc = 'upper left')
plt.show()

"""# Problem 4"""

X = np.linspace(-np.pi, np.pi, 15)
C = np.cos(X)
S = np.sin(X)

fig, ax = plt.subplots(2)
ax[0].plot(X, C, 'bs:')
ax[1].plot(X, S, 'go-')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
x = np.arange(0.0, 2.0, 0.01)
y = 1 + np.sin(2 * np.pi * x)

fig, ((ax1,ax2), (ax3,ax4)) = plt.subplots(2,2)
ax1.plot(x, y, c = 'green')
ax2.plot(x, y, c = 'blue')
ax3.plot(x, y, c = 'red')
ax4.plot(x, y, c = 'orange')
plt.show()

fig, axs = plt.subplots(2, 2)

# Now axs is a 2D array of Axes objects
axs[0, 0].plot([1, 2, 3], [4, 5, 6])
axs[0, 1].scatter([1, 2, 3], [4, 5, 6])
axs[1, 0].bar([1, 2, 3], [4, 5, 6])
axs[1, 1].hist([1, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 5])
plt.show()

